name: Java CI

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Build and run tests
        run: mvn test

      - name: Upload dependency snapshot
        uses: advanced-security/maven-dependency-submission-action@v5
        with:
          directory: .
          maven-args: dependency:tree -DoutputFile=dependency-tree.txt

